---
title: "betriuppsetning"
output: html_document
---

```{r}
library(dbplyr)
library(dplyr)
library(RMySQL)
library(tidyr)
library(MASS)
library(tidyverse)
library(ggplot2)
library(cowplot)
```

```{r, cache=T}
twDb<-src_mysql("tw_quizdb", host = "127.0.0.1", port = 3306, user = "iha6", password = "uOue2JeeVSMZE")
answer<-tbl(twDb,"answer")
lecture<-tbl(twDb,"lecture")
question<-tbl(twDb,"question")
host<-tbl(twDb,"host")
coinAward<-tbl(twDb,"coinAward")
lectureStudentSetting<-tbl(twDb,"lectureStudentSetting")
lectureStudentSetting%>%group_by(key)%>%summarise(stdev=sd(value,na.rm=T),stdevlog=sd(log2(value),na.rm=T))->stdevs

hashes<-read.csv("data/bighashfile.wide.txt",sep=" ",col.names = c("dir","qName","hash","hash2","hash3","numQ","notaType"),na.strings = ".")
hashes <- hashes %>% filter(numQ=="4")

plonePath<-unique(paste(hashes$dir,hashes$qName,sep=""))
plonePath<-as.data.frame(plonePath)
hashes$plonePath<-paste(hashes$dir,hashes$qName,sep="")
left_join(plonePath,as.data.frame(question))->myQuestions

answer%>%filter(timeStart>"2020-01-01 00:01:01")->answerRed
answerRed<-as.data.frame(answerRed)
inner_join(answerRed,myQuestions) -> myAnswer

myAnswer<-as.data.frame(myAnswer)
inner_join(myAnswer,hashes)->fullAnswerData
fullAnswerData
view(as.data.frame(fullAnswerData))
write_csv(x=fullAnswerData, path = "data/fullAnswerData.csv")
```



